let text = [
  "As I understand it, at the last count human information was doubling around every 18 months. Further to this, there is a point sometime around 2015 where human information is doubling every thousandth of a second. This means that in each thousandth of a second we will have accumulated more information than we have in the entire previous history of the world. At this point I believe that all bets are off. I cannot imagine the kind of culture that might exist after such a flashpoint of knowledge. I believe that our culture would probably move into a completely different state, would move past the boiling point, from a fluid culture to a culture of steam.",
  "True myth may serve for thousands of years as an inexhaustible source of intellectual speculation, religious joy, ethical inquiry, and artistic renewal. The real mystery is not destroyed by reason. The fake one is. You look at it and it vanishes. You look at the Blond Hero — really look — and he turns into a gerbil. But you look at Apollo, and he looks back at you. The poet Rilke looked at a statue of Apollo about fifty years ago, and Apollo spoke to him. “You must change your life,” he said. When true myth rises into consciousness, that is always its message. You must change your life.",
  "I have never found anywhere, in the domain of art, that you don't have to walk to. (There is quite an array of jets, buses and hacks which you can ride to Success; but that is a different destination.) It is a pretty wild country. There are, of course, roads. Great artists make the roads; good teachers and good companions can point them out. But there ain't no free rides, baby. No hitchhiking. And if you want to strike out in any new direction — you go alone. With a machete in your hand and the fear of God in your heart.",
  "I’ll make my report as if I told a story, for I was taught as a child on my homeworld that Truth is a matter of the imagination. The soundest fact may fail or prevail in the style of its telling: like that singular organic jewel of our seas, which grows brighter as one woman wears it and, worn by another, dulls and goes to dust. Facts are no more solid, coherent, round, and real than pearls are. But both are sensitive.",
  "To be an atheist is to maintain God. His existence or his nonexistence, it amounts to much the same, on the plane of proof. Thus proof is a word not often used among the Handdarata, who have chosen not to treat God as a fact, subject either to proof or to belief: and they have broken the circle, and go free. To learn which questions are unanswerable, and not to answer them: this skill is most needful in times of stress and darkness.",
  "Like all walls it was ambiguous, two-faced. What was inside it and what was outside it depended upon which side of it you were on. Looked at from one side, the wall enclosed a barren sixty-acre field called the Port of Anarres. [...] It was in fact a quarantine. The wall shut in not only the landing field but also the ships that came down out of space, and the men that came on the ships, and the worlds they came from, and the rest of the universe. It enclosed the universe, leaving Anarres outside, free. Looked at from the other side, the wall enclosed Anarres: the whole planet was inside it, a great prison camp, cut off from other worlds and other men, in quarantine.",
  "He had assumed that if you removed a human being’s natural incentive to work—his initiative, his spontaneous creative energy—and replaced it with external motivation and coercion, he would become a lazy and careless worker. But no careless workers kept those lovely farmlands, or made the superb cars and comfortable trains. The lure and compulsion of profit was evidently a much more effective replacement of the natural initiative than he had been led to believe."
];
